### PR TITLE
ignore sqlalchemy for now

### PR DESCRIPTION
**Pull request by c0state**

### CODE REVIEW

**Review by itajaja — APPROVED** [review]

**Comment by c0state** [comment]
Can you configure permissions for merging this @itajaja ?

**Comment by itajaja** [comment]
we said we were going to overhaul this to inherit from the 4c config, no?

**Comment by c0state** [comment]
> we said we were going to overhaul this to inherit from the 4c config, no?

Oh right. The repo does not configuration though it looks like. Also can't seem to dismiss review to avoid confusion.

**Comment by itajaja** [comment]
added this repo to the cloud team repos

**Comment by c0state** [comment]
Moved to #3

**Pull request closed without merging**
