### PR TITLE
Add GH packages token

### PR DESCRIPTION
**Pull request by AaronBuxbaum**

### CODE REVIEW

**Review by c0state — APPROVED** [review]
lgtm but how come that's needed? I thought `NPM_TOKEN` basically gets replaced with the github token and everything continues working?

**Comment by AaronBuxbaum** [comment]
> lgtm but how come that's needed? I thought `NPM_TOKEN` basically gets replaced with the github token and everything continues working?

renovate doesn't have access to github secrets

**Comment by c0state** [comment]
> > lgtm but how come that's needed? I thought `NPM_TOKEN` basically gets replaced with the github token and everything continues working?
> 
> renovate doesn't have access to github secrets

How come we didn't need similar config for `registry.npmjs.org` though?

**Comment by AaronBuxbaum** [comment]
> > > lgtm but how come that's needed? I thought `NPM_TOKEN` basically gets replaced with the github token and everything continues working?
> > 
> > 
> > renovate doesn't have access to github secrets
> 
> How come we didn't need similar config for `registry.npmjs.org` though?

good question! we did, actually, have the same exact config -- note here where I'm actually removing it now that it's in the upper level config
https://github.com/QuantumSi/web/pull/2271/files

**Pull request merged**
