### PR TITLE
Should we tag with "chore"?

### PR DESCRIPTION
**Pull request by c0state**

### CODE REVIEW

**Comment by taion** [comment]
can we have a centralized 4c one?

`semanticCommitTypeAll` doesn't override the default behavior of using `fix` for non-dev dep changes

**Comment by itajaja** [comment]
@c0state  are you sure we don't need `semanticCommits` as well?

**Comment by itajaja** [comment]
sure, we can have a centralized 4c, if we all agree on one

**Comment by taion** [comment]
daily updates, batch all non-major, chore for everything?

like https://github.com/react-bootstrap/react-bootstrap/blob/master/renovate.json but with `bump` for everything and a daily schedule

or i'd be ok w/weekly schedule too

**Comment by itajaja** [comment]
do you see any problem with `batch all non-major`? I think that if an update does break and you want to remove it, you'll have to do that every single day, manually, or edit the config file. they both are not great alternatives

**Comment by taion** [comment]
it's a fair point in principle, but how often do you see this coming up in practice? i feel like in general, my minor/patch upgrades go quite smoothly. they don't really break. and even when they do, it's because of trivial bugs in my own code

**Comment by c0state** [comment]
> @c0state are you sure we don't need `semanticCommits` as well?

I think you're right, added.

**Comment by itajaja** [comment]
relay 7 was an example. I think, when it does come up (and it does from time to time) it's a major pita

**Comment by itajaja** [comment]
oh well, touche. that was a major.

**Comment by itajaja** [comment]
to your point :P. ok, let's do it then. do you want to kick it off?

**Comment by c0state** [comment]
Closing, 4c shared renovate config is now at https://github.com/4Catalyzer/renovate-config

**Pull request closed without merging**
